[package]
name = "alice"
version = "3.0.0"
authors = ["LuNeder <luananeder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simulate = "0.3.0"
text_io = "0.1.8"
chrono = "0.4.19"
